apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: Immediate
parameters:
  type: gp2  # Or 'gp3' for newer generation EBS
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: ebs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
